<div class="service-footer row">
    <div class="col-lg-2 col-3 col-xl-3">
        <div class="icon-footer">
            <img src="<?php echo $block->getViewFileUrl('images/icon-3-footer.png');  ?>" alt="icon-3-footer">
        </div>
    </div>
    <div class="services-content col-lg-10 col-9 col-xl-9">
        <p><b>FREE SHIP WORLDWIDE</b></p>
        <p>On order over $200</p>
    </div>
</div>
<div class="service-footer row">
    <div class="col-lg-2 col-3 col-xl-3">
        <div class="icon-footer">
            <img src="<?php echo $block->getViewFileUrl('images/icon-2-footer.png');  ?>" alt="icon-2-footer">
        </div>
    </div>
    <div class="services-content col-lg-10 col-9 col-xl-9">
        <p><b>30-DAY RETURN PRODUCTS</b></p>
        <p>Moneyback Guarantee</p>
    </div>
</div>
<div class="service-footer row">
    <div class="col-lg-2 col-3 col-xl-3">
        <div class="icon-footer">
            <img src="<?php echo $block->getViewFileUrl('images/icon-1-footer.png');  ?>" alt="icon-1-footer">
        </div>
    </div>
    <div class="services-content col-lg-10 col-9 col-xl-9">
        <p><b>MEMBER SAFE SHOPPING</b></p>
        <p>Safe Shopping Guarantee</p>
    </div>
</div>