<div class="contact-top">
    <p><b>FOLLOW US ON</b></p>
    <div class="social-network">
        <a class="link" href="<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('fb-link-block')->toHtml(); ?>">
            <i class="fab fa-facebook-f"></i>
        </a>
    </div>
    <div class="social-network">
        <a class="link" href="<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('twitter-link-block')->toHtml(); ?>">
            <i class="fab fa-twitter"></i>
        </a>
    </div>
    <div class="social-network">
        <a class="link" href="<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('linkedin-link-block')->toHtml(); ?>">
            <i class="fab fa-linkedin-in"></i>
        </a>
    </div>
    <div class="social-network">
        <a class="link" href="<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('google-link-block')->toHtml(); ?>">
            <i class="fab fa-google-plus-g"></i>
        </a>
    </div>
    <div class="social-network">
        <a class="link" href="<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('pinterest-link-block')->toHtml(); ?>">
            <i class="fab fa-pinterest-p"></i>
        </a>
    </div>
    <div class="social-network">
        <a class="link" href="<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('youtube-link-block')->toHtml(); ?>">
            <i class="fab fa-youtube"></i>
        </a>
    </div>
</div>