<a href="#"><img src="<?php echo $block->getViewFileUrl('images/visa.png');  ?>" alt="visa"></a>
<a href="#"><img src="<?php echo $block->getViewFileUrl('images/mastercard.png');  ?>" alt="mastercard"></a>
<a href="#"><img src="<?php echo $block->getViewFileUrl('images/paypal.png');  ?>" alt="paypal"></a>
<a href="#"><img src="<?php echo $block->getViewFileUrl('images/american-express.png');  ?>" alt="american-express"></a>
<a href="#"><img src="<?php echo $block->getViewFileUrl('images/western-union.png');  ?>" alt="western-union"></a>