<div class="owl-carousel">
    <div> Your Content </div>
    <div> Your Content </div>
    <div> Your Content </div>
    <div> Your Content </div>
    <div> Your Content </div>
    <div> Your Content </div>
    <div> Your Content </div>
</div>
<script>
    require([
        'jquery',
        'owl'
    ], function ($) {
        $(document).ready(function () {
            $(document).ready(function(){
                $(".owl-carousel").owlCarousel();
            });
        });
    });
</script>
