<div class="contact-header">
    <i class="icon fas fa-phone-alt"></i>
    <div class="content-contact-header">
        <a href="tel:<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('phone-number-block')->toHtml(); ?>">
            <?php
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('phone-number-block')->toHtml();
            ?>
        </a>

        <a href="mailto:<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mail-block')->toHtml(); ?>">
            <?php
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mail-block')->toHtml();
            ?>
        </a>
    </div>
</div>
